function P = poten_mat_func_sb(in1)
%POTEN_MAT_FUNC_SB
%    P = POTEN_MAT_FUNC_SB(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Dec-2024 08:34:10

t2 = in1(2,:);
t3 = in1(3,:);
t4 = in1(4,:);
t5 = in1(5,:);
t6 = cos(t2);
t7 = cos(t3);
t8 = cos(t4);
t9 = cos(t5);
t10 = sin(t2);
t11 = sin(t3);
t12 = sin(t4);
t13 = sin(t5);
mt1 = [0.0;t9.*(t6.*t12+t7.*t8.*t10).*3.551688e+3+t7.*t10.*1.25131392e+6+t6.*t12.*2.9646e+2+t7.*t8.*t10.*2.9646e+2-t10.*t11.*t13.*3.551688e+3;t6.*t11.*1.25131392e+6+t6.*t8.*t11.*2.9646e+2+t6.*t7.*t13.*3.551688e+3+t6.*t8.*t9.*t11.*3.551688e+3;t9.*(t8.*t10+t6.*t7.*t12).*3.551688e+3+t8.*t10.*2.9646e+2+t6.*t7.*t12.*2.9646e+2];
mt2 = [t13.*(t10.*t12-t6.*t7.*t8).*(-3.551688e+3)+t6.*t9.*t11.*3.551688e+3;0.0;0.0;0.0;0.0];
P = [mt1;mt2];
end
